services:
  notesservice:
    build: 
      context: .
      dockerfile: NotesService/Dockerfile  
    ports:
      - "5000:80"  
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: my-postgres-new
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myNotesDb
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/dat